branch-defaults:
  main:
    environment: HuntIntelLive
    group_suffix: null
global:
  application_name: HuntIntelligence
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
